<?php /** @var \Amasty\Checkout\Block\Sales\Order\Info\Delivery $block */?>
<?php if ($fields = $block->getDeliveryDateFields()) : ?>
    <div class="delivery">
    <?php foreach ($fields as $field) : ?>
        <div class="delivery-field">
            <?= $block->escapeHtml(__($field['label'])); ?> : <?= $block->escapeHtml($field['value']); ?>
        </div>
    <?php endforeach; ?>
    </div>
<?php endif ?>
