<html>
<head>
</head>
<body>
<form id="realexpayments_hpp_form" method="POST" action="<?= $block->escapeHtml($block->getFormUrl()) ?>">
    <?php foreach ($block->getFormFields() as $field => $value) {
        $writer = new \Zend\Log\Writer\Stream(BP . '/var/log/logFile.log');
        $logger = new \Zend\Log\Logger();
        $logger->addWriter($writer);
        $logger->info($field."=>".$value);
        $inputName = htmlspecialchars($field, ENT_COMPAT | ENT_HTML401, 'UTF-8');
        $inputValue = isset($value) ?
            htmlspecialchars($value, ENT_COMPAT | ENT_HTML401, 'UTF-8') : '';
        ?>
        <!-- Begin HPP additional Fields -->
        <input type="hidden" name="HPP_CAPTURE_ADDRESS" value="true">
        <input type="hidden" name="HPP_DO_NOT_RETURN_ADDRESS" value="false">
        <!-- End HPP additional Fields -->
        <input
            type="hidden"
            name="<?= $block->escapeHtml($inputName) ?>"
            value="<?= $block->escapeHtml($inputValue) ?>" />
    <?php } ?>
</form>
<script>
     document.getElementById('realexpayments_hpp_form').submit();
</script>
</body>
</html>
